version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000

#  frontend:
#    restart: always
#    depends_on:
#      - backend
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"